# Generated by Django 4.2.4 on 2023-09-28 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm_Ependiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.date.today)),
                ('Bought_From', models.CharField(max_length=50, null=True)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('full_names', models.CharField(max_length=140)),
                ('Creation_Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('Current_Temperature', models.IntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='utils.farm_owners')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Name', models.CharField(max_length=25)),
                ('Irrigation_Sequence', models.JSONField()),
                ('Nutrition', models.JSONField()),
                ('Vulnerabilities_Mitigations', models.JSONField()),
                ('Estimatated_Harvest', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('Harvested', models.BooleanField(default=False)),
                ('Nursery_Date', models.DateField(null=True)),
                ('Germination_Date', models.DateField(null=True)),
                ('Transplanting_Date', models.DateField(null=True)),
                ('Flowering_Date', models.DateField(null=True)),
                ('Fruiting_Date', models.DateField(null=True)),
                ('First_Harvest_Date', models.DateField(null=True)),
                ('Harvest_End', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_Amount', models.IntegerField()),
                ('Sold_Amount', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Last_Update', models.DateField(default=datetime.date.today)),
                ('Measurement_Unit', models.CharField(max_length=10)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_products', to='utils.plant_allocation', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Things_UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='utils.farm_owners')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='utils.products_available')),
            ],
        ),
        migrations.CreateModel(
            name='Plot_subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_Number', models.IntegerField()),
                ('Previous_Moisture', models.IntegerField()),
                ('Current_Moisture', models.IntegerField()),
                ('Irrigation_On', models.BooleanField()),
                ('Last_Irrigation', models.DateField(default=datetime.date.today)),
                ('Active', models.BooleanField()),
                ('dimensions', models.JSONField()),
                ('Farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='utils.farms')),
            ],
        ),
        migrations.AddField(
            model_name='plant_allocation',
            name='plot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='utils.plot_subdivision'),
        ),
        migrations.CreateModel(
            name='Pesticide_Posession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Measurement_Unit', models.CharField(max_length=10)),
                ('ratio', models.CharField(max_length=20)),
                ('redundancy', models.IntegerField()),
                ('application', models.JSONField(null=True)),
                ('Expiry_Date', models.DateField()),
                ('flagged', models.BooleanField(default=False)),
                ('Issues', models.JSONField(null=True)),
                ('Expenditure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticides', to='utils.farm_ependiture')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide_Application_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Date', models.DateField(default=datetime.date.today)),
                ('purpose', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Ratio', models.IntegerField()),
                ('Plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='utils.plant_allocation')),
                ('pesticide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_application_hist', to='utils.pesticide_posession')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Harvest_Date', models.DateField()),
                ('Harvest_Amount', models.IntegerField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='utils.plant_allocation')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer_Posession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Measurement_Unit', models.CharField(max_length=10)),
                ('ratio', models.CharField(max_length=10)),
                ('redundancy', models.CharField(max_length=10)),
                ('application', models.JSONField()),
                ('Expiry_Date', models.DateField()),
                ('flagged', models.BooleanField(default=False)),
                ('Issues', models.JSONField()),
                ('Expenditure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='utils.farm_ependiture')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer_Application_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Date', models.DateField(default=datetime.date.today)),
                ('Amount', models.IntegerField()),
                ('Ratio', models.IntegerField()),
                ('Plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='utils.plant_allocation')),
                ('fertilizer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='F_application_hist', to='utils.fertilizer_posession')),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('Farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='utils.farms')),
            ],
        ),
        migrations.AddField(
            model_name='farm_ependiture',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure', to='utils.farms'),
        ),
        migrations.CreateModel(
            name='Farm_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('Measurement_Unit', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Expenditure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='utils.farm_ependiture')),
            ],
        ),
    ]
